### ISSUE TITLE
Stacktrace when starting the docker image

### ISSUE THREAD

**Issue by infoCup2017** [toludwig/golden-lemurs#2] opened 2017-01-26 00:06 UTC
Got a step further, now get this stack trace during start:

> starting server with webapp
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/app/classification/eval.py", line 4, in <module>
    from .GitHelper import get_all, fetch_repo
  File "/home/app/classification/GitHelper.py", line 354, in <module>
    selected_token = randint(0, len(tokens) - 1)
  File "/usr/lib/python3.4/random.py", line 218, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.4/random.py", line 196, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,0, 0)
** NG Live Development Server is running on http://0.0.0.0:8080. **
Hash: d946e4240ed1d54191ab                                                               
Time: 14268ms
chunk    {0} main.bundle.js, main.bundle.map (main) 47.7 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.map (styles) 27 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.map (vendor) 4.55 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.map (inline) 0 bytes [entry] [rendered]

Furthermore, I do not see any possibility to specify an entire file with all repos to be classified to your web application. Clocking on classify did not yield anything, probably because of the stack trace

PS: I am running Docker on Mac if this rings any bell

**Comment by infoCup2017** [comment] 2017-01-26 00:07
@toludwig: ☝️

**Comment by infoCup2017** [comment] 2017-01-26 00:08
Ah, forgot to insert any access token yet, might this be the issue?

**Comment by fabrichter** [comment] 2017-01-26 07:30
Yes, that is very likely the cause of this. You should use an access token with full 'repo' access rights because of our usage of the GraphQL API and insert it into classification/__init__.py. 

To classify an entire file, use:
```
./eval.py INPUT OUTPUT
```

This does require the docker image and thus our evaluation server to be running. Further details are also explained in our readme.

**Comment by jonico** [comment] 2017-01-26 17:14
Stacktrace is gone, but eval.py does not work against the server. I believe this is connected to the recent introduction of the limit parameter in the rate url, see my commit comment.

**Comment by fabrichter** [comment] 2017-01-26 17:36
This should be resolved by [https://github.com/toludwig/golden-lemurs/commit/4c21402214f62d846da258d7a2395b79dedf8d06](this fix). We tried to speed up the classification process by including a flag to reduce the amount of data we request from github and forgot to adapt our automated evaluation script, sorry for that.

**Comment by jonico** [comment] 2017-01-26 18:15
Closing as script is running through now.

**Closed** 2017-01-26 18:19 UTC
